### ISSUE TITLE
[Bug Report] Action Fails on Valid `.renovaterc`

### ISSUE THREAD

**Issue by kevinmatthes** [suzuki-shunsuke/github-action-renovate-config-validator#398]
Hello, @suzuki-shunsuke, and thank you for this GitHub Action!

With this issue, I would like to inform you about a bug I encountered when adding this Action to my CI pipeline.  In the respective repository, I formerly used `.renovaterc` as Renovate configuration file and Renovate itself accepted the file without any complaints.  When I added this Action to my CI workflow, the called validator complained about the file name as it would indicate an unknown format.  To make the validator accept the configuration file, I renamed it to `.renovaterc.json` and its validation passed without any problems.

Obviously, this is a conceptional mistake in the source code of the validator and not in this Action.  But as the bug will show up due to calling this Action on a file named `.renovaterc`, the output of the validator might lead to unnecessary confusion such that I assumed that you should rather know about this problem.

As a workaround, I would like to suggest that in case the input file is named `.renovaterc`, it could be renamed temporarily to `.renovaterc.json` in the wrapper shell script around the actual validator.  This would also prevent rejected configuration files in case any custom path should be given.

**Comment by suzuki-shunsuke** [comment]
Hi,

Thank you for your report.

I tested `renovate-config-validator` in my laptop, then I found `renovate-config-validator` has bugs.
They are issues of not my action but `renovate-config-validator` itself.

I guess these issues are same as what you reported.

I installed `renovate-config-validator` by npm.

```console
$ npm i -g renovate
```

```console
$ renovate --version
35.41.0
```

⚠️ The version is a bit old. I'll try the latest version [35.143.0](https://github.com/renovatebot/renovate/releases/tag/35.143.0) later.

If the file name is `renovate.json`, `renovate-config-validator` works fine.

renovate.json

```json
{
  "extends": [
    "config:base",
    "helpers:pinGitHubActionDigests"
  ],
  "packageRules": [
    {
      "matchManagers": [
        "gomod"
      ],
      "postUpdateOptions": []
    }
  ]
}
```

```console
$ renovate-config-validator   
 INFO: Validating renovate.json
 INFO: Config validated successfully
```

But if I renamed `renovate.json` to `.renovaterc`, renovate-config-validator failed.

```console
$ mv renovate.json .renovaterc
```

```console
$ renovate-config-validator
 WARN: .renovaterc could not be parsed
       "err": {
         "message": "Unsupported file type",
         "stack": "Error: Unsupported file type\n    at getParsedContent (/Users/shunsukesuzuki/.volta/tools/image/packages/renovate/lib/node_modules/renovate/lib/workers/global/config/parse/file.ts:31:13)\n    at /Users/shunsukesuzuki/.volta/tools/image/packages/renovate/lib/node_modules/renovate/lib/config-validator.ts:83:53"
       }
```

**Comment by suzuki-shunsuke** [comment]
I tried the latest version, but it has also the same bug.

```console
$ renovate --version
35.143.0
```

```console
$ renovate-config-validator   
 WARN: File could not be parsed
       "file": ".renovaterc",
       "err": {
         "message": "Unsupported file type",
         "stack": "Error: Unsupported file type\n    at getParsedContent (/Users/shunsukesuzuki/.volta/tools/image/packages/renovate/lib/node_modules/renovate/lib/workers/global/config/parse/file.ts:31:13)\n    at /Users/shunsukesuzuki/.volta/tools/image/packages/renovate/lib/node_modules/renovate/lib/config-validator.ts:87:53"
       }
```

**Comment by suzuki-shunsuke** [comment]
I'll report the issue to Renovate.
https://github.com/renovatebot/renovate/discussions

**Comment by suzuki-shunsuke** [comment]
I created a discussion.

https://github.com/renovatebot/renovate/discussions/22990
