### ISSUE TITLE
[Bug Report] Action only Validates JSON5

### ISSUE THREAD

**Issue by kevinmatthes** [suzuki-shunsuke/github-action-renovate-config-validator#399]
Another bug I found:  Renovate accepts both JSON and JSON5 as input formats whilst this Action only checks for JSON5 correctness.  This is a problem as it could happen that users actually intend to write JSON code which passes the validation by this Action but is finally rejected by Renovate because the configuration file contained features of JSON5.

Is it possible to adjust the shell script around the validator accordingly?

**Comment by suzuki-shunsuke** [comment]
Hi,

Thank you for your report.

But this action doesn't distinguish JSON and JSON5.

https://github.com/suzuki-shunsuke/github-action-renovate-config-validator/blob/6f635db0369ba2f1d9f9efd127c813fd72f9bd44/action.yaml

If this action doesn't work with JSON, probably that is a bug of `renovate-config-validator` itself.

Please tell us more details?

ref. https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce

**Comment by suzuki-shunsuke** [comment]
And if you found a bug of `renovate-config-validator`, please report it to Renovate.

https://github.com/renovatebot/renovate/discussions

**Comment by kevinmatthes** [comment]
Thank you for your quick answer.

> Please tell us more details?

For example, I configured the `lockFileMaintenance` for my project.  Therefore, the syntax is as follows:

```json
{
  "lockFileMaintenance": {
    "enabled": true
  }
}
```

This is valid in both JSON and JSON5.

The following example differs only in a trailing comma after `true`:

```json
{
  "lockFileMaintenance": {
    "enabled": true,
  }
}
```

If the file would be named `renovate.json`, for instance, this would be invalid as trailing commas are only allowed in JSON5 but not JSON.  Thus, the Renovate bot refuses this configuration and creates an issue with the bug report *although the linter does not find any issues*.  This is exactly the problem:  the validator and the bot seem to have different validation schemes for the same file.

**Comment by suzuki-shunsuke** [comment]
Thank you for your explanation.
Yeah, I think this is a bug of `renovate-config-validator`.

I created a discussion and pull request.

- https://github.com/renovatebot/renovate/discussions/22990
- https://github.com/renovatebot/renovate/pull/22991

`renovate-config-validator` validates `.json` with JSON5 parser. This is definitely a bug.

https://github.com/renovatebot/renovate/blob/ef6f0c7ffa2636c19e61932c4e8195fa01fde2c3/lib/workers/global/config/parse/file.ts#L18-L20

**Comment by suzuki-shunsuke** [comment]
FYI. You may be interested in this discussion.

- https://github.com/renovatebot/renovate/discussions/23002

**Comment by kevinmatthes** [comment]
Thank you for your support, you really helped me!  I will close this issue as well as the other one I opened as completed.
