### ISSUE TITLE
Strict not working

### ISSUE THREAD

**Issue by pippitt** [suzuki-shunsuke/github-action-renovate-config-validator#768]
Appears to be related to https://github.com/renovatebot/renovate/issues/30418 more of an FYI.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
This is the issue of not this action but Renovate itself, but I'll track the issue.

- https://github.com/renovatebot/renovate/issues/30418

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/github-action-renovate-config-validator/pull/770
- https://github.com/suzuki-shunsuke/github-action-renovate-config-validator/pull/772

**Comment by suzuki-shunsuke** [comment]
I've confirmed this issue was solved at the main branch.

- https://github.com/suzuki-shunsuke/test-github-action/pull/247

I'll release a new version.

**Comment by suzuki-shunsuke** [comment]
🎉 https://github.com/suzuki-shunsuke/github-action-renovate-config-validator/releases/tag/v1.1.1
